### PR TITLE
fix: Remove unsafe cast in ContinuousFlyout

### LINKED ISSUE #8884: Custom Toolbox Categories don't work if you have only custom categories
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

When using Blockly v11, I've encountered a limitation where setting all categories in a toolbox to use kind="custom_category" causes the toolbox to fail completely. If at least one category is set to the default category type (without kind="custom_category"), the toolbox renders correctly and functions normally.

This appears to be a regression introduced in Blockly v11, as the same configuration works without issues in earlier versions.

### Expected Behavior
All categories marked as `kind="custom_category"` should display and function normally with their custom icons and behaviors.
### Actual Behavior
When all categories are defined as `custom_category`, the toolbox fails to initialize and throws the following TypeError:
```
TypeError: Cannot read properties of null (reading 'getSelectedItem')
```

### Reproduction steps

1. Create a Custom Category Implementation.

```
class CustomToolboxCategory extends Blockly.ToolboxCategory {
    private iconClass_: string;

    constructor(categoryDef: any, toolbox: Blockly.Toolbox, opt_parent?: any) {
        super(categoryDef, toolbox, opt_parent);

        if (categoryDef['xml'] && categoryDef['xml'].getAttribute) {
            this.iconClass_ = categoryDef['xml'].getAttribute('iconClass') || '';
        } else if (categoryDef['iconClass']) {
            this.iconClass_ = categoryDef['iconClass'];
        }
    }

    public override createDom_(): HTMLDivElement {
        const categoryDom = super.createDom_();
        const labelElement = categoryDom.querySelector('.blocklyTreeLabel') as HTMLElement;
        
        if (labelElement && this.iconClass_) {
            const iconElement = document.createElement('i');
            iconElement.className = this.iconClass_;
            iconElement.style.marginRight = '8px';
            labelElement.insertBefore(iconElement, labelElement.firstChild);
        }

        return categoryDom as HTMLDivElement;
    }
}

```

2.  Register it

```
Blockly.registry.register(
    Blockly.registry.Type.TOOLBOX_ITEM,
    'custom_category',
    CustomToolboxCategory,
    true
);
```

3. Inject the workspace.

```
  const injectionOptions: Blockly.BlocklyOptions = {
    toolbox,
    trashcan: false,
    sounds: false,
    move: { scrollbars: true },
    zoom: { startScale: startScale, controls: false, wheel: false },
  };
  this.workspace = inject(this.blocklyDiv.nativeElement, injectionOptions);
}
```

3. Define a toolbox with only custom categories::

``` 
<xml id="toolbox">
  <category name="Category1" colour="#ff0000" kind="custom_category" iconClass="fa-solid fa-image"></category>
  <category name="Category2" colour="#00ff00" kind="custom_category" iconClass="fa-solid fa-image"></category>
  <category name="Category3" colour="#0000ff" kind="custom_category" iconClass="fa-solid fa-image"></category>

</xml>
```
**Result**: Toolbox fails to render with the mentioned TypeError.

4. Add at least one default category (no `kind="custom_category"`):`:

```
<xml id="toolbox">
  <category name="Category1" colour="#ff0000" kind="custom_category" iconClass="fa-solid fa-image"></category>
  <category name="Category2" colour="#00ff00"></category> <!-- default category -->
  <category name="Category3" colour="#0000ff" kind="custom_category" iconClass="fa-solid fa-image"></category>
</xml>
```
**Result**: Toolbox renders correctly and works without errors.

### Stack trace

```shell
free-world.page.ts:89 ERROR TypeError: Cannot read properties of null (reading 'getSelectedItem')
    at ContinuousFlyout.show (ContinuousFlyout.js:227:34)
    at init$$module$build$src$core$inject (blockly_compressed.js:430:277)
    at inject$$module$build$src$core$inject (blockly_compressed.js:423:278)
    at ************.renderBlockly (ngx-blockly.component.ts:119:28)
    at ************.ngOnChanges (ngx-blockly.component.ts:85:10)
    at ************.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:3139:14)
    at callHookInternal (core.mjs:4207:14)
    at callHook (core.mjs:4238:9)
    at callHooks (core.mjs:4188:17)
    at executeInitAndCheckHooks (core.mjs:4138:9)
```

### Screenshots

_No response_

### Browsers

_No response_

### PR DESCRIPTION
**Pull request by gonfunko**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

### Resolves

Fixes https://github.com/RaspberryPiFoundation/blockly/issues/8884

### Proposed Changes
This PR removes an unsafe cast that was assuming the parent toolbox is always non-null. I wasn't able to reproduce the behavior described in [#8884](https://github.com/RaspberryPiFoundation/blockly/issues/8884), but the stacktrace indicates that the toolbox was null on one of these lines, so handling that case should resolve it.

### CODE REVIEW

File: plugins/continuous-toolbox/src/ContinuousFlyout.ts [hunk 1]
```diff
@@ -72,8 +72,17 @@ export class ContinuousFlyout extends Blockly.VerticalFlyout {
    *
    * @returns Toolbox that owns this flyout.
    */
-  private getParentToolbox(): ContinuousToolbox {
-    return this.targetWorkspace.getToolbox() as ContinuousToolbox;
+  private getParentToolbox(): ContinuousToolbox | null {
+    const toolbox = this.targetWorkspace.getToolbox();
+    if (!toolbox || toolbox instanceof ContinuousToolbox) return toolbox;
+
+    console.log(
```
Comment (BenHenning) [inline plugins/continuous-toolbox/src/ContinuousFlyout.ts]: Should this maybe be a warning or error, instead? It seems like a case where the configuration is actually broken and we're trying to sort of recover as best as we can (which is to basically do nothing I suppose).

**Review by BenHenning — APPROVED** [review]
Thanks @gonfunko! This seems a reasonable defensive thing to do, though I wonder if the console log should be a bit more warning/error esque to represent the severity of the fact that the configuration is pretty clearly broken in such a case.

**Comment by BenHenning** [comment]
Also: I suppose it's possible that the flyout is simply null and not the wrong type, right? The stacktrace, as far as I can tell, is just failing on it being null either due to mismatched type or the value being null (unless I'm misreading it...).

File: plugins/continuous-toolbox/src/ContinuousFlyout.ts (hunk 1 above)
Comment (gonfunko) [reply plugins/continuous-toolbox/src/ContinuousFlyout.ts]: Bumped it to a warning, good call.

**Comment by gonfunko** [comment]
Yes, it could just be null, in which case this should still not throw. All it was doing was trying to select the first category, and if there is no toolbox that just becomes a no-op now which seems reasonable.
