### PR TITLE
fix: handle comment moves and resizes in content-highlight

### LINKED ISSUE #2330: Content-highlight doesn't update for workspace comment move events
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

workspace-content-highlight

### Description

If you move workspace comments or add them to the workspace, they don't update the content highlight. However if you move a block, the content highlight updates to highlight everything including the comments.

### Reproduction steps

1. Load the following JSON into the workspace.
```js
{
  "workspaceComments": [
    {
      "height": 100,
      "width": 120,
      "id": "o`-uR}#Q,qg#1LUorXg5",
      "x": 131.890625,
      "y": 326,
      "text": "Say something..."
    },
    {
      "height": 100,
      "width": 120,
      "id": "*CHb18}Td!%xT~MTvk!N",
      "x": 327.5572814941406,
      "y": 698.3333129882812,
      "text": "Say something..."
    }
  ],
  "blocks": {
    "languageVersion": 0,
    "blocks": [
      {
        "type": "controls_if",
        "id": "0NAT)tSk}AALHd#HIB%x",
        "x": 213,
        "y": 162
      }
    ]
  }
}
```
3. Move the comments around.
4. Observe how the highlight does not update.

### Stack trace

_No response_

### Screenshots

_No response_

### Additional Info

This has to be tested against v11.

### PR DESCRIPTION
**Pull request by maribethb**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

### Resolves

Fixes #2330 

### Proposed Changes

Rebases #2400 now that all the plugins use a compatible version of blockly. Thanks to @johnnesky for the commits.

### CODE REVIEW

File: plugins/content-highlight/src/index.ts [hunk 1]
```diff
@@ -185,7 +186,7 @@ export class ContentHighlight {
   private onChange(event: Blockly.Events.Abstract) {
     if (event.type === Blockly.Events.THEME_CHANGE) {
       this.applyColor();
-    } else if (contentChangeEvents.indexOf(event.type) !== -1) {
+    } else if ((contentChangeEvents as string[]).indexOf(event.type) !== -1) {
```
Comment (gonfunko) [inline plugins/content-highlight/src/index.ts]: Is the `as string[]` necessary given that `contentChangeEvents` is explicitly typed as `string[]`?

Comment (maribethb) [reply plugins/content-highlight/src/index.ts]: no, fixed

**Review by gonfunko — APPROVED** [review]
